services:
  postgres:
    image: postgres:16-alpine
    container_name: stockpilot-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - stockpilot-data:/var/lib/postgresql/data

volumes:
  stockpilot-data:
