spring:
  application:
    name: stockpilot

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

yahoo-finance:
  api-key: ${YAHOO_FINANCE_API_KEY:}
  api-host: ${YAHOO_FINANCE_API_HOST:yahoo-finance15.p.rapidapi.com}
  base-url: https://yahoo-finance15.p.rapidapi.com

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /docs
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /docs
