-- =====================================================================
-- V1 Baseline: 초기 스키마
-- 모든 CREATE는 IF NOT EXISTS 로 멱등성 보장 — 부분 적용된 dev DB도 안전하게 보강.
-- baseline-on-migrate=true + baseline-version=0 → 비어있지 않은 DB는 V0 로 baseline
-- 후 V1 을 실행하여 누락 객체만 생성. 빈 DB는 V1 을 처음부터 적용.
-- 이후 모든 변경은 V2, V3, ... 마이그레이션 파일로 추적.
-- =====================================================================


-- ---------------------------------------------------------------------
-- Stock 도메인
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS sectors (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    name_kr    VARCHAR(100),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6),
    CONSTRAINT uk_sectors_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS stocks (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol          VARCHAR(20)  NOT NULL,
    name            VARCHAR(200) NOT NULL,
    name_kr         VARCHAR(200),
    market          VARCHAR(10)  NOT NULL,
    sector_id       BIGINT,
    is_starter_pack BOOLEAN      NOT NULL,
    description     TEXT,
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    deleted_at      TIMESTAMP(6),
    CONSTRAINT fk_stocks_sector FOREIGN KEY (sector_id) REFERENCES sectors(id)
);

CREATE TABLE IF NOT EXISTS daily_prices (
    id          BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id    BIGINT         NOT NULL,
    trade_date  DATE           NOT NULL,
    open_price  NUMERIC(18, 4) NOT NULL,
    high_price  NUMERIC(18, 4) NOT NULL,
    low_price   NUMERIC(18, 4) NOT NULL,
    close_price NUMERIC(18, 4) NOT NULL,
    volume      BIGINT         NOT NULL,
    change_rate NUMERIC(8, 4),
    created_at  TIMESTAMP(6)   NOT NULL,
    updated_at  TIMESTAMP(6)   NOT NULL,
    deleted_at  TIMESTAMP(6),
    CONSTRAINT fk_daily_prices_stock FOREIGN KEY (stock_id) REFERENCES stocks(id)
);


-- ---------------------------------------------------------------------
-- Watchlist 도메인
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS watchlists (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    session_id VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS watchlist_items (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    watchlist_id BIGINT       NOT NULL,
    stock_id     BIGINT       NOT NULL,
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL,
    deleted_at   TIMESTAMP(6),
    CONSTRAINT fk_watchlist_items_watchlist FOREIGN KEY (watchlist_id) REFERENCES watchlists(id),
    CONSTRAINT fk_watchlist_items_stock     FOREIGN KEY (stock_id)     REFERENCES stocks(id)
);


-- ---------------------------------------------------------------------
-- Knowledge: 투자 용어 사전
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS term_categories (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(50)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    display_order INTEGER      NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6) NOT NULL,
    deleted_at    TIMESTAMP(6),
    CONSTRAINT uk_term_categories_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS investment_terms (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT       NOT NULL,
    name        VARCHAR(100) NOT NULL,
    full_name   VARCHAR(200),
    summary     VARCHAR(500) NOT NULL,
    description TEXT,
    formula     VARCHAR(500),
    example     TEXT,
    difficulty  VARCHAR(20)  NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    deleted_at  TIMESTAMP(6),
    CONSTRAINT uk_investment_terms_name      UNIQUE (name),
    CONSTRAINT fk_investment_terms_category  FOREIGN KEY (category_id) REFERENCES term_categories(id)
);

CREATE TABLE IF NOT EXISTS investment_term_relations (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term_id         BIGINT       NOT NULL,
    related_term_id BIGINT       NOT NULL,
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    deleted_at      TIMESTAMP(6),
    CONSTRAINT uk_term_relation_pair      UNIQUE (term_id, related_term_id),
    CONSTRAINT fk_term_relations_term     FOREIGN KEY (term_id)         REFERENCES investment_terms(id),
    CONSTRAINT fk_term_relations_related  FOREIGN KEY (related_term_id) REFERENCES investment_terms(id)
);


-- ---------------------------------------------------------------------
-- Knowledge: 경제지표
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS economic_indicators (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code              VARCHAR(50)  NOT NULL,
    name              VARCHAR(100) NOT NULL,
    unit              VARCHAR(20)  NOT NULL,
    frequency         VARCHAR(20)  NOT NULL,
    source            VARCHAR(20)  NOT NULL,
    source_stat_code  VARCHAR(50)  NOT NULL,
    source_item_code  VARCHAR(50),
    description       TEXT,
    why_it_matters    TEXT,
    related_term_id   BIGINT,
    display_order     INTEGER      NOT NULL,
    created_at        TIMESTAMP(6) NOT NULL,
    updated_at        TIMESTAMP(6) NOT NULL,
    deleted_at        TIMESTAMP(6),
    CONSTRAINT uk_economic_indicators_code  UNIQUE (code),
    CONSTRAINT fk_economic_indicators_term  FOREIGN KEY (related_term_id) REFERENCES investment_terms(id)
);

CREATE TABLE IF NOT EXISTS indicator_observations (
    id           BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    indicator_id BIGINT         NOT NULL,
    observed_at  DATE           NOT NULL,
    value        NUMERIC(19, 6) NOT NULL,
    created_at   TIMESTAMP(6)   NOT NULL,
    updated_at   TIMESTAMP(6)   NOT NULL,
    deleted_at   TIMESTAMP(6),
    CONSTRAINT uk_indicator_observation              UNIQUE (indicator_id, observed_at),
    CONSTRAINT fk_indicator_observations_indicator   FOREIGN KEY (indicator_id) REFERENCES economic_indicators(id)
);
CREATE INDEX IF NOT EXISTS idx_indicator_observed_at ON indicator_observations (indicator_id, observed_at DESC);


-- ---------------------------------------------------------------------
-- Knowledge: 공시 (DART)
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS dart_corps (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corp_code   VARCHAR(8)   NOT NULL,
    corp_name   VARCHAR(200) NOT NULL,
    stock_code  VARCHAR(10),
    stock_id    BIGINT,
    modify_date DATE,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    deleted_at  TIMESTAMP(6),
    CONSTRAINT uk_dart_corps_corp_code UNIQUE (corp_code),
    CONSTRAINT fk_dart_corps_stock     FOREIGN KEY (stock_id) REFERENCES stocks(id)
);

CREATE TABLE IF NOT EXISTS disclosures (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corp_code       VARCHAR(8)   NOT NULL,
    corp_name       VARCHAR(200) NOT NULL,
    stock_id        BIGINT,
    receipt_no      VARCHAR(14)  NOT NULL,
    report_name     VARCHAR(500) NOT NULL,
    disclosure_type VARCHAR(20)  NOT NULL,
    submitted_at    TIMESTAMP(6) NOT NULL,
    submitter_name  VARCHAR(200),
    remark          VARCHAR(20),
    dart_url        VARCHAR(500) NOT NULL,
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    deleted_at      TIMESTAMP(6),
    CONSTRAINT uk_disclosures_receipt_no UNIQUE (receipt_no),
    CONSTRAINT fk_disclosures_stock      FOREIGN KEY (stock_id) REFERENCES stocks(id)
);
CREATE INDEX IF NOT EXISTS idx_disclosure_submitted_at      ON disclosures (submitted_at DESC);
CREATE INDEX IF NOT EXISTS idx_disclosure_stock_submitted   ON disclosures (stock_id, submitted_at DESC);
CREATE INDEX IF NOT EXISTS idx_disclosure_type_submitted    ON disclosures (disclosure_type, submitted_at DESC);
